"""add bot token

Revision ID: 033d555bd83c
Revises: ac7505d38233
Create Date: 2020-07-17 16:52:21.503430

"""
from alembic import op
import sqlalchemy as sa
from app import db
from app.models import GeneralSetting
from uuid import uuid4


# revision identifiers, used by Alembic.
revision = '033d555bd83c'
down_revision = 'ac7505d38233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('general_settings', sa.Column('bot_token', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###

    g = GeneralSetting.query.get(1)
    g.bot_token = str(uuid4())
    db.session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('general_settings', 'bot_token')
    # ### end Alembic commands ###
